name: Docker

on: push
  

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_version: [ "0.14.2" ]
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan Docker Image
        uses: azure/container-scan@v0
        with:
          image-name: hello-world
      - name: Show the secret
        run: echo "My secret is" ${{secrets.MSG_VAR}} 
        
        
