name: Docker CD

on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
        - uses: Azure/container-scan@v0
          with:
            image-name: ghcr.io/sanjanasenthilkumar/github-actions-for-packages/tic-tac-toe:${{ github.sha }}


   
      


