name: Docker CD

on: push
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read

    strategy:
      fail-fast: false
      matrix:
        language: [javascript]
     
    # Specify the container in which actions will run
    container:
      image: ghcr.io/sanjanasenthilkumar/github-actions-for-packages/tic-tac-toe:sha-7d23c90
      
      

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
   
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
